# Generated by Django 3.0.4 on 2020-05-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipapp01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_register_user',
            name='userphone',
            field=models.IntegerField(blank=True, db_column='phone', null=True),
        ),
    ]
