# Generated by Django 3.0.4 on 2020-05-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipapp01', '0002_top_register_user_userphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_register_user',
            name='userphone',
            field=models.IntegerField(blank=True, db_column='phone', max_length=100, null=True),
        ),
    ]
