# Generated by Django 3.0.4 on 2020-05-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipapp01', '0005_top_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_register_user',
            name='user_group',
            field=models.ManyToManyField(to='vipapp01.Top_User_Group'),
        ),
    ]
