# Generated by Django 3.0.4 on 2020-06-05 02:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('vipapp01', '0006_top_register_user_user_group'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='top_user_group',
            managers=[
                ('groupmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
