# Generated by Django 3.0.4 on 2020-07-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipapp01', '0007_auto_20200605_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_register_user',
            name='update_image',
            field=models.ImageField(blank=True, null=True, upload_to='vipapp01'),
        ),
    ]
