# Generated by Django 3.0.4 on 2020-08-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vipapp01', '0007_auto_20200605_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='top_register_user',
            options={'verbose_name': '用户组'},
        ),
    ]
