# Generated by Django 3.0.4 on 2020-09-04 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vipapp01', '0008_auto_20200813_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='function_Case_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_parameter', models.TextField(max_length=50000)),
                ('describe', models.TextField(max_length=2000)),
                ('function_Preconditions', models.TextField(max_length=2000)),
            ],
            options={
                'db_table': 'function_Case_Content',
            },
        ),
        migrations.CreateModel(
            name='Interface_Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.CharField(blank=True, max_length=4000, null=True)),
                ('server', models.CharField(max_length=2000)),
                ('port', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.TextField(max_length=50000)),
                ('parameter', models.TextField(blank=True, max_length=50000, null=True)),
                ('method', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=100)),
                ('Assertion', models.TextField(blank=True, max_length=50000, null=True)),
                ('state', models.IntegerField(default=3, max_length=10)),
            ],
            options={
                'db_table': 'Interface_Case',
            },
        ),
        migrations.CreateModel(
            name='Modular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modular_name', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('modular_Sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vipapp01.Modular')),
            ],
            options={
                'db_table': 'Modular',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('describe', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Test_Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=2000)),
                ('test_mode', models.IntegerField(default=1, max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('case_type', models.IntegerField(default=1, max_length=10)),
                ('case_priority', models.IntegerField(default=1, max_length=10)),
                ('case_result', models.IntegerField(default=3, max_length=10)),
                ('case_Maintainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vipapp01.Top_User_Group')),
                ('case_modular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vipapp01.Modular')),
            ],
            options={
                'db_table': 'Test_Case',
            },
        ),
        migrations.AlterModelOptions(
            name='top_register_user',
            options={},
        ),
        migrations.AlterModelTable(
            name='top_role',
            table='top_role',
        ),
        migrations.CreateModel(
            name='Test_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=2000)),
                ('plan_state', models.IntegerField(default=1, max_length=10)),
                ('phase', models.IntegerField(default=4, max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('plan_Maintainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vipapp01.Top_Register_User')),
                ('plan_case', models.ManyToManyField(to='vipapp01.Test_Case')),
                ('plan_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vipapp01.Project')),
            ],
        ),
        migrations.AddField(
            model_name='test_case',
            name='case_plan',
            field=models.ManyToManyField(to='vipapp01.Test_Plan'),
        ),
        migrations.AddField(
            model_name='test_case',
            name='case_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vipapp01.Project'),
        ),
        migrations.CreateModel(
            name='PeInt_Case_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_Preconditions', models.TextField(max_length=2000)),
                ('content_parameter', models.ManyToManyField(to='vipapp01.Interface_Case')),
            ],
            options={
                'db_table': 'PeInt_Case_Content',
            },
        ),
        migrations.AddField(
            model_name='modular',
            name='modular_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vipapp01.Project'),
        ),
        migrations.AddField(
            model_name='interface_case',
            name='content_parameter',
            field=models.ManyToManyField(to='vipapp01.PeInt_Case_Content'),
        ),
    ]
