# Generated by Django 3.0.4 on 2020-09-04 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vipapp01', '0009_auto_20200904_0334'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test_plan',
            table='Test_Plan',
        ),
    ]
