# Generated by Django 3.0.4 on 2020-09-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipapp01', '0012_auto_20200915_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface_case',
            name='it_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
