# Generated by Django 3.0.4 on 2020-10-23 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vipapp01', '0013_interface_case_it_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='interface_case',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='function_case_content',
            name='function_Test_Case',
        ),
        migrations.RemoveField(
            model_name='interface_case',
            name='content_parameter',
        ),
        migrations.RemoveField(
            model_name='interface_case',
            name='createuser',
        ),
        migrations.RemoveField(
            model_name='peint_case_content',
            name='content_parameter',
        ),
        migrations.AddField(
            model_name='function_case_content',
            name='function_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vipapp01.Test_Case'),
        ),
        migrations.AddField(
            model_name='interface_case',
            name='create_user',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peint_case_content',
            name='associated_interface',
            field=models.ManyToManyField(null=True, to='vipapp01.Interface_Case'),
        ),
        migrations.AddField(
            model_name='peint_case_content',
            name='describe',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='peint_case_content',
            name='interface_test_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vipapp01.Test_Case'),
        ),
        migrations.AddField(
            model_name='test_plan',
            name='plan_case',
            field=models.ManyToManyField(to='vipapp01.Test_Case'),
        ),
        migrations.AlterField(
            model_name='function_case_content',
            name='describe',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='interface_case',
            name='it_name',
            field=models.CharField(default='test', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interface_case',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='top_register_user',
            name='user',
            field=models.CharField(db_column='username', max_length=200),
        ),
    ]
