[uwsgi]
# nginx转发此服务器地址
#socket=127.0.0.1:8000
# uwsgi做服务器
#http=192.168.8.174:8000
http = 127.0.0.1:8111

# 项目路径
chdir = /Users/zhouliudong/djangogit/Django/django03
#项目启动文件
wsgi-file = django03/wsgi.py
# 进程线程设置
processes = 4
threads = 2
# 是否需要主进程
master = True
#PID 文件路径
pidfile = uwsgi.pid
#添加日志
daemonize = uwsgi.log


